services:

  influxdb:
    image: influxdb:latest
    container_name: influxdb
    ports:
      - "8086:8086"
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=qardio-user
      - DOCKER_INFLUXDB_INIT_PASSWORD=encryptedpassword
      - DOCKER_INFLUXDB_INIT_ORG=qardio
      - DOCKER_INFLUXDB_INIT_BUCKET=qardio-bucket
      - DOCKER_INFLUXDB_INIT_RETENTION=10w
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=admin-token
    volumes:
      - influxdb_data:/var/lib/influxdb

volumes:
  influxdb_data:
    driver: local